### PR TITLE
initial work for proposals that would cause major change, also: refactoring, optimizations and some rewrites and complied to pep 0008

### PR DESCRIPTION
**Pull request by iaacornus**
I insist to use Python 3.10 instead of using shebangs (`#!/usr/bin/env python`), specifically due to structural pattern matchings from [pep 0634](https://peps.python.org/pep-0634/), walrus operator (albeit controversial) from [pep 0572](https://peps.python.org/pep-0572/), and other improvements. This pull requests contains some initial work for transition for python 3.10, some optimizations such as removal of repetitive calls of functions and use of better modules.

This also includes rewrite of the logger using logging module from Python with Logging handler from Rich module, since it is more efficient than manually doing the work.

There are also non significant changes I've made, but it should have helped the program, such as use of `Raise SystemExit(message)` instead of `print(message)` and `exit(int)`. `with open(...) ...` were also used instead of bare `open`. As well as compliance to [pep 0008](https://peps.python.org/pep-0008/), since pep8 helps to create a codebase that is more readable thus easier to maintain, the compliance to pep 0008 explains the remove of `try`-`except` statement in imports section, and strict limiting to 79 (80) character/line, among other changes.

Dynamic user agents were also used instead of static user agent using the `modules.random_user_agent.py` (a rewrite of [random_user_agent](https://github.com/Luqman-Ud-Din/random_user_agent) since it is no longer maintained) which draws random user agent from `modules/user_agents/` folder (data from [@Luqman-Ud-Din](https://github.com/Luqman-Ud-Din)'s [random_user_agent](https://github.com/Luqman-Ud-Din/random_user_agent).

There are more works to do in this PR, but I first want to know the opinion of current contributors and maintainers regarding this significant change in codebase before proceeding. I also want to note that I agree that python 3.10 is cutting edge technology, if bleeding edge is too exaggerated, but it should help the program significantly due to the significant changes introduced lately, particularly pep 0634, [0613](https://peps.python.org/pep-0613/), and [0612](https://peps.python.org/pep-0612/).

Here are the changes and features I propose:

- [ ] use type hinting (this is another part where python 3.10 significantly helps, since instead of importing from `Typing`, hintings can be directly used, e.g. `Type.List[...]` -> `list[...]`. This creates a more readable and easier to maintain code.
- [ ] code base clean up, since there are a lot of dangling global variables, which is against python's recommendation, and complex use of `if`-`else`, instead of `try`-`except`-`else` and `match`-`case`.
- [ ] restructuring of the code base, I suggest to use the `src` for easier package configuration.
- [ ] complete removal of global variables and limiting the variables to function
- [ ] rewrite of commandline implementation
- [ ] packaging for pypi
- [ ] features
    - [ ] update feature, I noticed that the program uses `nmap`, which seems to be from another repo, thus it should receive the updates from the particular module.
- [ ] unit tests for easier rewrite and implementation of new functions, I suggest to use `pytest`
- [ ] Installation of dependecies by putting them in `requirements.txt`, or by packaging this for pypi, thus having `pip` to take care of it, instead of self containg them.

I help and is willing to give some of my time to implement the features that would be accepted. I also note that some of listed features can be implemented without completely rewriting to python 3.10, but I insist a transition as I reasoned above.

NOTE: these changes are not guaranteed to work since they are not tested yet. However, they are expected to work since no major change has been done yet.

### CODE REVIEW

**Comment by GamehunterKaan** [comment]
This is a huge pull request. And also the first time I am facing something like this. I am definitely looking forward to collaborate.

**Comment by iaacornus** [comment]
perhaps, if you don't mind, maybe you can create another branch where the pull requests from both ends would be pulled for easier merging with the main branch later on?

**Comment by GamehunterKaan** [comment]
> perhaps, if you don't mind, maybe you can create another branch where the pull requests from both ends would be pulled for easier merging with the main branch later on? and so that the main branch would be the stable branch

Done!

**Comment by iaacornus** [comment]
greetings,

i'd like to continue on this one, if it would be ok @GamehunterKaan . Although i apologize for the previous state of my PR and its abrupt discontinuation without any notice. would it be ok if i'll continue this PR?

**Pull request closed without merging**
